### ISSUE TITLE
How to Debug with Rustrover IDE?

### ISSUE THREAD

**Issue by rz2606** [CSCI-SHU-410-SE-Project/Deskulpt#22]
As Rustrover offers more comprehensive features and a comprehensive search function, it is relatively easy to use. The hope is to provide a convenient configuration for running and debugging

![38835f50587ccceb21a12b1cbd5fe57](https://github.com/CSCI-SHU-410-SE-Project/Deskulpt/assets/114788055/25f7cc50-5bbb-4040-b028-e7431a48468a)

As shown above, The Rust code did not enter the debugging breakpoint.

**Comment by Xinyu-Li-123** [comment]
Maybe you could refer to Tauri's and JetBrain's tutorial on debugging with RustRover.
- [Rust tutorial](https://tauri.app/zh-cn/v1/guides/debugging/rustrover/)
- [JetBrain's tutorial](https://www.jetbrains.com/help/rust/debugging-code.html)

**Comment by Charlie-XIAO** [comment]
I'm going to close this as resolved. Feel free to reopen if there are further questions. After all, even if you fail to figure out how to debug, you can just print the variables of interest locally, then run with `npm run tauri dev` or `npm run tauri build -- --debug` in the terminal.
