### ISSUE TITLE
BUG widget-specific api wrapper doesn't work on linux

### ISSUE THREAD

**Issue by Xinyu-Li-123** [CSCI-SHU-410-SE-Project/Deskulpt#50]
As is described in the title, `import apis from "@deskulpt-tests/apis` won't work on linux. I have tested on both Ubuntu 20.04 with `libwebkit2gtk-4.0-dev` and Ubuntu 22.04 with the `libwebkit2gtk-4.0-dev` and `libwebkit2gtk-4.1-dev`, and I will be refering to these environments when I use the work "linux" below. But this should be the case whenever the linux webview is powered by WebKitGTK.

This issue is likely related to how the linux webview engine `WebKitGTK` manage access control, in specific, access from a webpage to blob url created in another webpage of the same origin but different path. When a widget import from `@deskulpt-tests/apis`, what really happens is as follows (for details, see #35)
- `manager` window creates a blob url to a javascript file that is initialized for a specific widget
- The blob url replaces imports from `@deskulpt-tests/apis` in the compiled widget js code
- Compiled widget js code runs in the `canvas` window, and the canvas window request for the blob url to import the apis.

Normally, `manager` and `canvas` windows run two webpages of the same origin at different path (e.g. `localhost:1420/views/index.html` and `localhost:1420/views/canvas.html`). A blob url created in `manager` window's webapge should thus be accessible in the `canvas` window's webpage. This is the case on Windows and MacOS, but not so in Linux. More specifically, the WebKitGTK-powered webpages doesn't support sharing blob on different path within same origin, because this works in a normal browser in linux.

**Comment by Charlie-XIAO** [comment]
@Xinyu-Li-123 Please check if #47 fixes this issue. If so we can close.

**Comment by Xinyu-Li-123** [comment]
Yes, #47 fixes this issue. Deskulpt can now run on Ubuntu.
